---

ansible_connection: network_cli
ansible_network_os: ios
ansible_user: cisco
ansible_ssh_pass: cisco
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: cisco

interfaces_info: sh ip int br
ntp_config: ntp server 10.1.2.2
