---

ansible_connection: network_cli
ansible_network_os: ios
ansible_user: cisco
ansible_password: cisco
ansible_become: yes
ansible_become_method: enable
ansible_become_pass: cisco

textfsm_templates: "/home/vagrant/repos/ansible_modules/ntc-ansible/ntc-templates/templates"
ntc_platform: cisco_ios
