---

- name: Run show commands on routers
  hosts: r1


  tasks:

    - name: Clear interface counters
      cli_command:
        command: clear counters e0/0
        prompt: 'Clear "show interface" counters on this interface'
        answer: y

    - name: Clear interface counters
      cli_command:
        command: clear counters {{ item }}
        prompt: 'Clear "show interface" counters on this interface'
        answer: y
      loop: [e0/2, e0/1, e0/0]

    - name: Send commands
      cli_command:
        command: "{{ item }}"
      loop: ["sh ip int br", "sh clock"]
