---

- name: Run cfg commands on router
  hosts: r1,r2,r3
  gather_facts: true

  tasks:

    - name: Debug var
      debug:
        var: ansible_network_resources

    - name: Config NTP
      cli_config:
        config: "{{ lookup('file', 'templates/ntp.txt') }}"

    - name: Config OSPF
      cli_config:
        config: "{{ lookup('template', 'templates/{{ansible_network_os}}_ospf.j2') }}"

        # ansible-playbook 4_ios_config_src_jinja_facts.yml --diff
