---

- name: Run show commands on router
  hosts: 192.168.100.1
  gather_facts: false
  connection: local

  tasks:

    - name: Run sh ip int br
      ntc_show_command:
        connection: ssh
        platform: "cisco_ios"
        command: "sh ip int br"
        host: "{{ inventory_hostname }}"
        username: "{{ ansible_username }}"
        password: "{{ ansible_password }}"
        template_dir: "{{textfsm_templates }}"
      register: result

    - debug: var=result
