---

- name: Run show commands on router
  hosts: 192.168.100.2

  tasks:

    - name: Run ntc ansible tasks
      block:
        - include: tasks/ntc_show.yml
          vars:
            ntc_command: "sh clock"

        - debug: var=ntc_result

        - include: tasks/ntc_show.yml
          vars:
            ntc_command: "sh ip int br"

        - debug: var=ntc_result

      delegate_to: "localhost"

